# Generated by Django 5.1.1 on 2024-10-30 21:03

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='brokerage_commission_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3, null=True),
        ),
    ]
