# Generated by Django 5.1.1 on 2024-11-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_options_offer_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerimages',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Offer Image', 'verbose_name_plural': 'Offer Images'},
        ),
        migrations.AlterModelOptions(
            name='offervideos',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Offer Video', 'verbose_name_plural': 'Offer Videos'},
        ),
    ]
