# Generated by Django 5.1.1 on 2024-10-22 07:02

import datetime
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('post_code', models.PositiveIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('TH', 'Townhouse'), ('AP', 'Apartment'), ('C', 'Condo'), ('V', 'Villa'), ('CN', 'Caravan')], max_length=100)),
                ('rooms', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('bought_date', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 10, 22))])),
                ('property_condition', models.CharField(choices=[('R', 'Ready to sell'), ('S', 'Sold'), ('F', 'For sale'), ('Rp', 'Repaired'), ('U', 'Under repair')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
                'unique_together': {('country', 'town', 'address', 'post_code')},
            },
        ),
        migrations.CreateModel(
            name='PropertyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilities_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('utilities', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('notary_taxes_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('notary_taxes', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('profit_tax_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('profit_tax', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('municipality_taxes_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('municipality_taxes', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('advertising_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('advertising', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('administrative_fees_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('administrative_fees', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('insurance_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('insurance', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('expected_expenses_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('expected_expenses', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=7)),
                ('expense_details', models.TextField(blank=True, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_expenses', to='properties.property')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='PropertyFinancialInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_price_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('initial_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10)),
                ('repair_cost_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('repair_cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10)),
                ('is_credited', models.BooleanField()),
                ('credited_amount_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('credited_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_financial_information', to='credits.credit')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_financial_information', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Financial Information',
                'verbose_name_plural': 'Property Financial Information',
            },
        ),
        migrations.CreateModel(
            name='PropertyForSale',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.property')),
                ('listed_price_currency', djmoney.models.fields.CurrencyField(choices=[('GBP', 'British Pound'), ('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('CHF', 'Swiss Franc'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='EUR', editable=False, max_length=3)),
                ('listed_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10)),
                ('is_furnished', models.BooleanField(default=False)),
                ('list_description', models.TextField()),
                ('listed_date', models.DateField(auto_now_add=True)),
                ('listed_property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_for_sales', to='properties.property')),
            ],
            bases=('properties.property',),
        ),
    ]
