# Generated by Django 5.1.1 on 2024-10-30 21:03

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_owner_alter_property_bought_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyexpense',
            name='administrative_fees_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='advertising_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='expected_expenses_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='insurance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='municipality_taxes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='notary_taxes_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='profit_tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='utilities_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyfinancialinformation',
            name='credited_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='propertyfinancialinformation',
            name='credited_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='propertyfinancialinformation',
            name='initial_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyfinancialinformation',
            name='repair_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='propertyforsale',
            name='listed_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
    ]
