# Generated by Django 5.1.1 on 2024-10-30 21:05

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyexpense_administrative_fees_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfinancialinformation',
            name='credited_amount',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True),
        ),
    ]
