# Generated by Django 5.1.1 on 2024-11-11 12:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_bought_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bought_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 11, 11))]),
        ),
    ]
