# Generated by Django 5.1.1 on 2024-11-17 13:49

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_propertyexpense_other_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bought_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 11, 17))]),
        ),
    ]
