# Generated by Django 5.1.1 on 2024-11-18 11:04

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_bought_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyexpense',
            name='expense_details',
        ),
        migrations.AlterField(
            model_name='property',
            name='bought_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='bathroom_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Bathroom Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='electrical_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Electrical Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='facade_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Facade Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='floors_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Floors Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='kitchen_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Kitchen Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='other_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Other Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='plumbing_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Plumbing Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='walls_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Walls Repair Expenses'),
        ),
        migrations.AlterField(
            model_name='propertyexpense',
            name='windows_doors_repair_expenses',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=7, null=True, verbose_name='Windows and Doors Repair Expenses'),
        ),
        migrations.CreateModel(
            name='PropertyExpenseNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('expense_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('expense_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7)),
                ('expense_type', models.CharField()),
                ('expanse_date', models.DateField(blank=True, null=True)),
                ('relates_expenses', models.ManyToManyField(related_name='expenses_notes', to='properties.propertyexpense')),
            ],
        ),
    ]
