# Generated by Django 5.1.1 on 2024-11-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0012_remove_propertyexpense_expense_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyexpensenotes",
            name="relates_expenses",
        ),
        migrations.AddField(
            model_name="propertyexpensenotes",
            name="relates_expenses",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses_notes",
                to="properties.propertyexpense",
            ),
            preserve_default=False,
        ),
    ]
