# Generated by Django 5.1.1 on 2024-11-27 11:32

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_alter_property_property_condition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Townhouse", "Townhouse"),
                    ("Apartment", "Apartment"),
                    ("Condo", "Condo"),
                    ("Villa", "Villa"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="administrative_fees",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Administrative Fees",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="advertising",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Advertising",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="bathroom_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Bathroom Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="electrical_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Electrical Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="expected_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Expected Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="facade_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Facade Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="floors_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Floors Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="insurance",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Insurance",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="kitchen_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Kitchen Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="municipality_taxes",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Municipality Taxes",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="notary_taxes",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Notary Taxes",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="other_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Insurance",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="other_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Other Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="plumbing_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Plumbing Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="profit_tax",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Profit Tax",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="roof_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Insurance",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="utilities",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Utilities",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="walls_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Walls Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="windows_doors_repair_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                verbose_name="Windows and Doors Repair Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpensenotes",
            name="expense_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                max_digits=8,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Expense amount cannot be negative."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="propertyfinancialinformation",
            name="credited_amount",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Credited amount cannot be negative."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="propertyfinancialinformation",
            name="initial_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"),
                        message="Initial property price cannot be negative.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="propertyfinancialinformation",
            name="is_credited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="propertyfinancialinformation",
            name="repair_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Repair cost cannot be negative."
                    )
                ],
            ),
        ),
    ]
