# Generated by Django 5.1.1 on 2024-11-27 12:15

import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0016_alter_property_property_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyexpense",
            name="expected_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=8,
                null=True,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Expected expenses cannot be negative."
                    )
                ],
                verbose_name="Expected Expenses",
            ),
        ),
    ]
