# Generated by Django 5.1.1 on 2024-12-06 22:01

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_alter_propertyexpense_administrative_fees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyexpense",
            name="credit_interest",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
                verbose_name="Credit Interest",
            ),
        ),
        migrations.AddField(
            model_name="propertyexpense",
            name="credit_interest_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "Euro")],
                default="EUR",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyexpense",
            name="other_expenses",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                null=True,
                verbose_name="Other Expenses",
            ),
        ),
    ]
