# Generated by Django 5.1.1 on 2024-12-11 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0009_alter_credit_credit_amount_and_more"),
        ("properties", "0021_alter_property_year_of_built_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfinancialinformation",
            name="credit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_financial_information",
                to="credits.credit",
            ),
        ),
    ]
