# Generated by Django 5.1.1 on 2024-10-30 21:03

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='amounts_paid_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BGN', 'Bulgarian Lev'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3),
        ),
    ]
