# Generated by Django 5.1.1 on 2024-11-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_creditpayment_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['-credit_term'], 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
    ]
