# Generated by Django 5.1.1 on 2024-11-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0006_alter_credit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="credit_type",
            field=models.CharField(
                choices=[
                    ("Business Credit", "Business Credit"),
                    ("Personal Credit", "Personal Credit"),
                    ("Mortgage", "Mortgage"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="creditpayment",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_payments",
                to="credits.credit",
            ),
        ),
    ]
