# Generated by Django 5.1.1 on 2024-11-27 11:32

import django.core.validators
import djmoney.models.fields
import djmoney.models.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0008_alter_creditpayment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit",
            name="credit_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Credit amount must be greater than 0."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="credit_interest",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Interest must be greater than 0."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="credit",
            name="monthly_payment",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Monthly payment must be greater than 0."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="creditpayment",
            name="interest_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Interest amount must be greater than 0."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="creditpayment",
            name="principal_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[
                    djmoney.models.validators.MinMoneyValidator(
                        Decimal("0"), message="Principal amount must be greater than 0."
                    )
                ],
            ),
        ),
    ]
