# Generated by Django 5.1.1 on 2024-10-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
    ]
