# Generated by Django 5.1.1 on 2024-12-07 20:01

import FixToFlip.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_title_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'Comment must be at least 20 characters long'), FixToFlip.validators.bad_words_validator]),
        ),
    ]
