# Generated by Django 5.1.1 on 2024-11-09 08:22

import FixToFlip.accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="baseaccount",
            managers=[
                ("objects", FixToFlip.accounts.managers.BaseAccountManager()),
            ],
        ),
    ]
