# Generated by Django 5.1.1 on 2024-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro')], default='EUR', max_length=3, null=True),
        ),
    ]
