# Generated by Django 5.1.1 on 2024-11-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_preferred_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ["user"],
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
