# Generated by Django 5.1.1 on 2024-11-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Company', 'Company')], max_length=10, null=True),
        ),
    ]
