# Generated by Django 5.1.1 on 2024-11-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_rename_facebook_url_profile_company_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="company_location_country",
            new_name="company_location",
        ),
    ]
